# specify 1 or more environments to be created by the provision command

environments:
  # example
  # unique name:
  #   exposed_port_to_job: 9092
  #   exposed_port:
  #   - 9092
  #   - 8082
  #   - 8080
  #   job_env:
  #     START_DATE: "start date "
  #     END_DATE: "end date"
  #     EQUITY: "equity name"
  #   args_sets:
  #     deployment:
  #     - -c
  #     - "\"\""
  #     job:
  #     - -c
  #     - "\" java $JAVA_OPTS -Ddb=h2 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -jar /app.jar -s $EQUITY -r $START_DATE $END_DATE \""

  spx20180201:
    exposed_port_to_job: 9092
    exposed_port:
    - 9092
    - 8082
    - 8080
    job_env:
      START_DATE: "2018-01-01"
      END_DATE: "2018-02-01"
      EQUITY: "SPX"
    args_sets:
      deployment:
      - -c
      - "\"\""
      job:
      - -c
      - "\" java $JAVA_OPTS -Ddb=h2 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -jar /app.jar -s $EQUITY -r $START_DATE $END_DATE \""

  vxx20180301:
    exposed_port_to_job: 9092
    exposed_port:
    - 9092
    - 8082
    - 8080
    job_env:
      START_DATE: "2018-01-01"
      END_DATE: "2018-02-01"
      EQUITY: "SPX"
    args_sets:
      deployment:
      - -c
      - "\"\""
      job:
      - -c
      - "\" java $JAVA_OPTS -Ddb=h2 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -jar /app.jar -s $EQUITY -r $START_DATE $END_DATE \""