environments:
  env1:
    exposed_port: 5432
    args_sets:
      deployment:
      - -c
      - "\"psql -h 127.0.0.1 -p 5432  -U postgres -tAc \\\"CREATE TABLE IF NOT EXISTS sample ( message TEXT NOT NULL); INSERT INTO sample (message) VALUES ('Hello, world $$POD_NAME');\\\" && sleep 600 \""
      job:
      - -c
      - "\"for i in {1..5}; do psql -U postgres -h $SERVICE_URL -tAc 'SELECT * FROM sample' && sleep 3; done\""

  env2:
    exposed_port: 5432
    args_sets:
      deployment:
      - -c
      - "\"psql -h 127.0.0.1 -p 5432  -U postgres -tAc \\\"CREATE TABLE IF NOT EXISTS sample ( message TEXT NOT NULL); INSERT INTO sample (message) VALUES ('Hello, mars $$POD_NAME');\\\" && sleep 600 \""
      job:
      - -c
      - "\"for i in {1..5}; do psql -U postgres -h $SERVICE_URL -p $SERVICE_EXPOSED_PORT -tAc 'SELECT * FROM sample' && sleep 3; done\""