import os

CONFIG_FILE = os.getcwd() + "/config.yml"
TEMPLATES = os.getcwd() + "/templates/"
ENVIRONMENTS_CONFIG_KEY = "environments"
SERVICE_TEMPLATE = TEMPLATES + "service.jinja"
DEPLOYMENT_TEMPLATE = TEMPLATES + "deployment.jinja"
JOB_TEMPLATE = TEMPLATES + "job.jinja"
DEPLOYMENT_SUFFIX = "-deployment"
SERVICES_SUFFIX = "-svc"
JOBS_SUFFIX = "-job"
EXPOSED_PORT_KEY = "exposed_port"
ARGS_KEY = "args_sets"
ENV_KEY = "job_env"
GARBAGE_COLLECTOR = "gc-svc"
GARBAGE_COLLECTOR_URL = GARBAGE_COLLECTOR + ":8080"
DAEMON_SET_CONFIG_LOCATION = os.getcwd() + "/daemon_set/"
EXPOSED_PORT_TO_JOB_KEY = "exposed_port_to_job"
AUTH_CONFIG_FILE_NAME = os.getcwd() + "/auth-config.yml"
AUTH_SERVER_KEY = "server"
AUTH_USER_NAME_KEY = "username"
AUTH_PASSWORD_KEY = "password"
AUTH_EMAIL_KEY = "email"